services:
  will-you-be-my-valentine:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
